### ISSUE TITLE
how do clippy args work?

### ISSUE THREAD

**Issue by danieleades** [qernal/github-actions-rust-clippy#24]
i'm attempting to add an `--all-targets` flag to this action like so-

```yaml
      - uses: actions/checkout@v3
      - uses: qernal/github-actions-rust-clippy@v2.0.0
        with:
          args: --all-targets
          rust_version: nightly-2022-10-18
```

but i'm getting this error-

```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "--all-targets": executable file not found in $PATH: unknown.
```

how should args be passed?
